#define MAGIC_NUMBER 'O'

#define SET_BAUD_RATE _IOWR(MAGIC_NUMBER, 1, int)
#define SET_NO_STOP_BITS _IOWR(MAGIC_NUMBER, 2, int)
#define SET_DIRECTION_WRITE _IOW (MAGIC_NUMBER, 3, int)
//#define DEFAULT_DATA _IOW(MAGIC_NUMBER, 4, int)
#define DEFAULT_DATA 1
#define SET_TOGGLE_FREQ _IOW(MAGIC_NUMBER, 4, int)
